import * as analytics from './admin/analytics.js';
import * as blog from './admin/blog.js';
import * as deals from './admin/deals.js';
import * as expenses from './admin/expenses.js';
import * as index from './admin/index.js';
import * as inventory from './admin/inventory.js';
import * as menu from './admin/menu.js';
import * as orders from './admin/orders.js';
import * as settings from './admin/settings.js';
import * as shared from './admin/shared.js';

Object.assign(window, analytics);
Object.assign(window, blog);
Object.assign(window, deals);
Object.assign(window, expenses);
Object.assign(window, index);
Object.assign(window, inventory);
Object.assign(window, menu);
Object.assign(window, orders);
Object.assign(window, settings);
Object.assign(window, shared);
