export const welcomeLangs = [
  "Welcome to Bigi Awasaana",
  "Bienvenidos a Bigi Awasaana",
  "به بیگی آواسانا خوش آمدید",
  "Bienvenue chez Bigi Awasaana",
  "Willkommen bei Bigi Awasaana",
  "Benvenuti da Bigi Awasaana",
  "Bem-vindos ao Bigi Awasaana",
  "Welkom bij Bigi Awasaana",
  "Добро пожаловать в Биги Авасана",
  "欢迎来到比吉阿瓦萨纳",
  "ビギ・アワサナへようこそ",
  "비기 아와사나에 오신 것을 환영합니다",
  "مرحباً بكم في بيجي أواسانا",
  "ברוכים הבאים לביגי אוואסאנה",
  "بيګي اواسانا ته ښه راغلاست",
  "بگی اواسانا میں خوش آمدید",
  "बिगी आवासाना में आपका स्वागत है",
  "Bigi Awasaana'ya hoş geldiniz",
  "Välkommen till Bigi Awasaana",
  "Velkommen til Bigi Awasaana",
  "Tervetuloa Bigi Awasaanaan",
  "Witamy w Bigi Awasaana",
  "Vítejte v Bigi Awasaana",
  "Üdvözöljük a Bigi Awasaanában",
  "Bine ați venit la Bigi Awasaana",
  "Καλώς ήρθατε στο Μπίγκι Αουασάνα",
  "Ласкаво просимо до Бігі Авасана",
  "Selamat datang di Bigi Awasaana",
  "Selamat datang ke Bigi Awasaana",
  "Maligayang pagdating sa Bigi Awasaana",
  "Chào mừng đến với Bigi Awasaana",
  "ยินดีต้อนรับสู่ บิกิ อาวาซานา",
  "বিগি আওয়াসানায় স্বাগতম",
  "બિગી આવાસાનામાં આપનું સ્વાગત છે",
  "ਬਿਗੀ ਆਵਾਸਾਨਾ ਵਿੱਚ ਜੀ ਆਇਆਂ ਨੂੰ",
  "பிகி ஆவாசானாவுக்கு வரவேற்கிறோம்",
  "బిగి ఆవాసానాకు స్వాగతం",
  "ಬಿಗಿ ಆವಾಸಾನಾಕ್ಕೆ ಸುಸ್ವಾಗತ",
  "ബിഗി ആവാസാനയിലേക്ക് സ്വാഗതം",
  "बिगी आवासानामा स्वागत छ",
  "බිගි ආවාසානා වෙත සාදරයෙන් පිළිගනිමු",
  "Karibu Bigi Awasaana",
  "ወደ ቢጊ አዋሳና እንኳን ደህና መጡ",
  "Soo dhawoow Bigi Awasaana",
  "Barka da zuwa Bigi Awasaana",
  "Ẹ kú àbọ̀ sí Bigi Awasaana",
  "Nnọọ na Bigi Awasaana",
  "Siyakwamukela kuBigi Awasaana",
  "Wamkelekile kuBigi Awasaana",
  "Welkom by Bigi Awasaana",
  "Mirë se vini në Bigi Awasaana",
  "Բարի գալուստ Բիգի Ավասանա",
  "Bigi Awasaana-ya xoş gəlmisiniz",
  "Ongi etorri Bigi Awasaanara",
  "Сардэчна запрашаем у Бігі Авасана",
  "Dobrodošli u Bigi Awasaana",
  "Добре дошли в Биги Авасана",
  "Benvinguts a Bigi Awasaana",
  "Tere tulemast Bigi Awasaanasse",
  "Benvidos a Bigi Awasaana",
  "კეთილი იყოს თქვენი მობრძანება ბიგი ავასანაში",
  "Byenveni nan Bigi Awasaana",
  "Velkomin til Bigi Awasaana",
  "Fáilte go Bigi Awasaana",
  "Бигі Авасанаға қош келдіңіздер",
  "Биги Авасанага кош келиңиздер",
  "Bi xêr hatin Bigi Awasaana",
  "Laipni lūdzam Bigi Awasaana",
  "Sveiki atvykę į Bigi Awasaana",
  "Wëllkomm bei Bigi Awasaana",
  "Добредојдовте во Биги Авасана",
  "Merħba fi Bigi Awasaana",
  "Nau mai ki Bigi Awasaana",
  "Биги Авасанад тавтай морил",
  "ဘီဂီ အာဝါဆာနာ မှ ကြိုဆိုပါတယ်",
  "សូមស្វាគមន៍មកកាន់ ប៊ីហ្គី អាវ៉ាសាណា",
  "ຍິນດີຕ້ອນຮັບສູ່ ບິກິ ອາວາຊານາ",
  "Добродошли у Биги Авасана",
  "Vitajte v Bigi Awasaana",
  "Dobrodošli v Bigi Awasaana",
  "Ба Биги Авасана хуш омадед",
  "Bigi Awasaana-ga xush kelibsiz",
  "Croeso i Bigi Awasaana",
  "Fàilte gu Bigi Awasaana",
  "Afio mai i Bigi Awasaana",
  "Talitali fiefia ki Bigi Awasaana",
  "Bula vinaka ki Bigi Awasaana",
  "Murakaza neza kuri Bigi Awasaana",
  "Tongasoa eto amin'ny Bigi Awasaana",
  "Titambirei kuBigi Awasaana",
  "Re u amohela ho Bigi Awasaana",
  "Bonvenon al Bigi Awasaana",
  "Salvete ad Bigi Awasaana",
  "歡迎來到比吉阿瓦薩納",
  "Vælkomin til Bigi Awasaana",
  "ברוכים הבאים צו ביגי אוואסאנא",
  "Tigaza Bigi Awasaana",
  "أهلا بيك في بيجي أواسانا"
];